- hosts: httpd
  tasks:
   - name: copy files
     copy: src=roles/httpd/files/ dest=/ owner=root group=root mode=0755
   - name: change mode on apache log directory.
     file:
       path: /var/log/httpd
       mode: 0755
  roles:
   - role: geerlingguy.apache
   - role: geerlingguy.logstash
     logstash_elasticsearch_hosts:
      - http://node01:9200
      - http://node02:9200
      - http://node03:9200
#     logstash_ssl_dir: "/etc/pki/logstash"
     logstash_ssl_certificate_file: logstash.crt
     logstash_ssl_key_file: logstash.key
#     logstash_local_syslog_path: /var/log/syslog
#     logstash_monitor_local_syslog: true
     logstash_enabled_on_boot: yes

#   - role: geerlingguy.filebeat
#     filebeat_create_config: true
#     filebeat_prospectors:
#      - input_type: log
#        paths:
#         - "/var/log/httpd/access_log"
#     filebeat_output_logstash_enabled: true
#     filebeat_output_logstash_hosts:
#      - "192.168.33.51:5000"
#     
