- hosts: search
  roles:
   - role: ansible-role-elasticsearch
     elasticsearch_network_host: 0.0.0.0
     elasticsearch_use_cluster: yes
     elasticsearch_cluster_name: search
   - role: geerlingguy.kibana
#   - role: geerlingguy.logstash
#     logstash_elasticsearch_hosts:
#      - http://192.168.33.51:9200
#      - http://192.168.33.52:9200
#     logstash_ssl_dir: "/etc/pki/logstash"
#     logstash_ssl_certificate_file: logstash.crt
#     logstash_ssl_key_file: logstash.key
#     logstash_local_syslog_path: /var/log/syslog
#     logstash_monitor_local_syslog: true
#     logstash_enabled_on_boot: yes

